### PR TITLE
pump up the Functor

### PR DESCRIPTION
**Pull request by stew**
- add an examples project
- add an example for Functor
- add some derrived methods on functor

### CODE REVIEW

**Comment by mpilquist** [comment]
:+1:

**Comment by mpilquist** [comment]
@stew `fproduct` does the same thing as `zipWith` -- any preference?

**Comment by stew** [comment]
oh oops, sorry I didn't notice, I don't have a preference

**Comment by mpilquist** [comment]
OK cool -- I think I'll keep `zipWith` then. At least until someone wants to argue for something different. :)

**Comment by stew** [comment]
want a PR for that?

**Comment by mpilquist** [comment]
Either way -- I'll probably work on more laws and instances later today/tonight so if you beat me to it, I'll merge.

**Pull request merged**
